name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  NODE_VERSION: 22.x

jobs:
  tests-unit:
    name: âœ… Tests unitaires
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: ðŸŸ¢ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: ðŸ“¦ Installation des dÃ©pendances
        run: npm i

      - name: ðŸ§ª Lancement des tests unitaires
        env:
          PORT: 5005
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
          NODE_ENV: development
          DEBUG: false
          FRONTEND_URL: http://localhost:5173
        run: npm run coverage
